### ISSUE TITLE
0.8.1 problems

### ISSUE THREAD

**Issue by grfrey** [opiopan/fsmapper#5]
Hi, um trying the fsmapper 0.8.1, the screen shows the pfd mfd image, the events and actions shows ALL commands but nothing happens on the game.

https://user-images.githubusercontent.com/94576331/207054962-78a7e9bb-ff01-45eb-b144-acfdfea2e063.MOV

**Comment by opiopan** [comment]
Which action name did you seen on message console, send_event or execute_rpn?
If it's the later, It seems that MobiFlight WASM module version is old.
Try latest version of MobiFlight WASM module.

**Comment by grfrey** [comment]
I updated mobiflight and now is working Fine. Thanks

**Comment by opiopan** [comment]
I'm glad the problem was solved.
